modules:
    ADVENCHANTMENTS: true
    EFFECTWEAPONS: true
    ORESTONES: true
    HEADHUNT: true
    PUMPKINBANDIT: true
    OWNHEALTH: true
    HOME: true
    SPEED: true
    DISTANCESHOT: true
    RANDOMCHESTS: true
    CUSTOMENCHANTS: true
    TOKEN: true