name: CLUtil
main: de.craftlancer.clutil.CLUtil
version: {$project.version}
description: Some Utility Stuff for Craftlancer
depend: [SpeedAPI, TagAPI, PermissionsEx]
commands:
  sneak:
    description: Toggles sneak
    usage: /sneak
  statsme:
    description: Shows K/D Stats
    usage: /statsme
  find:
    description: Find other players with your compass
    usage: /find <player>
  togglearrow:
    description: Toggle usage of poison arrows
    usage: /togglearrow
  home:
    description: Teleport to your home!
    usage: /home
  building:
    description: Build
    usage: /building
permissions:
    cl.util.krieger:
        default: false
    cl.util.berserk:
        default: false
    cl.util.waldlaufer:
        default: false
    cl.util.shear:
        default: false
    cl.util.reload:
        default: op
    cl.util.find:
        default: false
    cl.util.sneak:
        default: false
