name: CLUtil
main: de.craftlancer.clutil.CLUtil
version: ${project.version}
description: Some Utility Stuff for Craftlancer
depend: [SpeedAPI, TagAPI, PermissionsEx, SkillLevels, Towny, WayOfShadows]
commands:
  find:
    description: Find other players with your compass
    usage: /find <player>
  home:
    description: Teleport to your home!
    usage: /home
  debugger:
    description: equip
    usage: /equip
  class:
    description: Change your class
    usage: /class <classname>
permissions:
    cl.util.krieger:
        default: false
    cl.util.berserk:
        default: false
    cl.util.waldlaufer:
        default: false
    cl.util.shear:
        default: false
    cl.util.reload:
        default: op
    cl.util.find:
        default: false
    cl.util.sneak:
        default: false
